[package]
name = "rp2040-panic-usb-boot"
version = "0.6.0"
authors = ["Jan Niehusmann <jan@gondor.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
description = "On panic, boot to USB mode implemented in ROM"
readme = "README.md"
repository = "https://github.com/jannic/rp2040-panic-usb-boot/"
homepage = "https://github.com/jannic/rp2040-panic-usb-boot/"
keywords = ["panic-handler", "panic-impl", "no-std", "embedded"]

[dependencies]
cortex-m = "0.7.7"
rp2040-hal = { version = "0.10.0", default-features = false }

[dev-dependencies]
rp-pico = "0.9.0"
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
