[build]
# Instruction set of Cortex-M0+
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]

rustflags = [
  # use the Tlink.x scrip from the cortex-m-rt crate
  "-C", "link-arg=-Tlink.x",
]

runner = "elf2uf2-rs -d"
